### PR TITLE
Add test parsing, signing, finalizing a psbt made by core

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

Parse PSBT created with bitcoind 23.0 and same descriptor as `get_test_tr_single_sig_xprv()` and `get_test_tr_with_taptree_xprv`. I used these steps to get core to generate the test PSBTs : https://hackmd.io/@notmandatory/taproot-testing.

### Notes to the reviewers

I went down a little rabbit hole trying to create a tr() descriptor in core that could be partially signed, but finally realized that it's not currently possible, see "[What wallet support for Taproot will be included in Bitcoin Core v22.0?](https://bitcoin.stackexchange.com/questions/106904/what-wallet-support-for-taproot-will-be-included-in-bitcoin-core-v22-0)".

This PR doesn't include creating PSBTs from `bdk` that can be signed by core, this looks to be done in `blockchain_tests` `test_taproot_key_spend()` and `test_taproot_script_spend()`.

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature
* [ ] I've updated `CHANGELOG.md`

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by notmandatory** [comment]
@afilini I think this is ready to go, I was only able to come up with two small tests, if you think we need other scenarios let me know.

**Comment by afilini** [comment]
Sorry I missed this PR when you submitted it the first time, I'll review it now and merge to my branch.

I just wanted to clarify that in the blockchain tests we are not asking core to sign, we do everything inside bdk. We just broadcast the final transaction so that the node checks its validity and complains if something is wrong.

**Comment by afilini** [comment]
It's interesting that they don't really have any metadata inside the PSBT, and that they still add the `non_witness_utxo` even though it's not necessary anymore.

Did you try running `utxoupdatepsbt` to see if they would add more metadata? BDK can sign those PSBTs anyway because just before signing we add our own, but I would be curious to see if we can sign even with what comes from core (and if they set them differently compared to ourselves)

**Comment by notmandatory** [comment]
Thanks for the tips! I will check with `utxoupdatepsbt` and make sure we can sign and finalize those. Will also try digging in a bit more on the decoded core PSBTs vs BDK PSBTs to understand the diffs too.

**Comment by notmandatory** [comment]
I was able to convert one of my tests to a blockchain test, so psbt is generated in core as part of the test. Is this a reasonable way to do it? It's a little messy because `bitcoincore_rpc` doesn't have all the calls we need, but at least this way is easier to reproduce with future versions of core (won't need to generate new PSBTs manually).

**Comment by notmandatory** [comment]
@afilini I accidentally force pushed my commits to your branch, sorry! I backed them out, but please check it matches your local. I fixed my set-upstream so shouldn't happen again.

**Comment by afilini** [comment]
Yeah my branch looks good!

I also think that's a little messy but it's extra test coverage so I'll take it for now.

**Review by afilini — APPROVED** [review]

**Comment by notmandatory** [comment]
Do you think the basic approach of using `bitcoincore_rpc` to create PSBTs in core to sign/finalize with `bdk`? If so I'll see if I can help get some of the missing RPC calls added to `bitcoincore_rpc` starting with https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/199.

**Comment by afilini** [comment]
I like the idea but I don't really like adding these as "blockchain tests" because those are supposed to test syncing.

Maybe we can have a different section where we have tests that get access to a bitcoind instance and we can test interoperability with core.

**Pull request merged**
